name: Pytest

on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main, master]

permissions:
  contents: write
  pull-requests: write
  checks: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v4

      # Pythonセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13" 
          cache: pip
          
      # ライブラリインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"
           
      # # ユニットテスト実行
      - name: Run tests
        env:
          PYTHONPATH: server/src:client/src
        run: |
          pytest --cov=server/src --cov=client/src --cov-report=term-missing
      # テスト結果をコメントする
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt